import React from 'react'
import type {Metadata} from 'next'
import './globals.css'
import {SidebarProvider} from '@/context/SidebarContext'
import {ThemeProvider} from '@/context/ThemeContext'
import {UserProvider} from '@/context/UserContext'
import QueryProvider from "@/context/QueryContext"

export const metadata: Metadata = {
    title: {
        template: 'Nolink | %s',
        default: 'Nolink',
    },
    description: 'Generated by create next app'
}

export default async function RootLayout({children}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
        <body className={`dark:bg-stone-950`}>
        <ThemeProvider>
            <SidebarProvider>
                <QueryProvider>
                    <UserProvider>
                        {children}
                    </UserProvider>
                </QueryProvider>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    )
}
